name: 'geoBoundaryBot'
description: 'I provide automated checks for the geoBoundaries project.'
inputs:
  check:
    description: 'The type of check you would like to run.'
    required: true
    default: 'file'
runs:
  using: "composite"
  steps:
    -run: echo Hello.
    -run: echo ${{ inputs.check }}
           



      
      

      

 
